name: 'Enable Github Automerge'
description: 'Enable Github auto-merge for specific pull-requests'
branding:
  icon: 'git-merge'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  merge-method:
    description: 'Preferred merge method for automatic merges.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
