# Always rebuild the distributable action, so that we can release from `main` at any point
# This doubles-up as a test, and also prevents tampering!

name: Rebuild
on:
  push:
    branches-ignore:
      - main

jobs:
  rebuild:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: actions/setup-node@main
        with:
          node-version-file: ".nvmrc"
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d
        with:
          file_pattern: --force dist/*
          commit_message: "chore: 🛠 Rebuild action!"
