# Attempt to lint & build the action.
# We *separately* rebuild the action, this build is used as a status check.
name: Test
on:
  pull_request:
  schedule:
    # Scheduled build so failures are noticed quicker.
    - cron: "17 4 * * 2,5"

jobs:
  # Lint & build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: actions/setup-node@main
        with:
          node-version-file: ".nvmrc"
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run format-check
      - name: Build
        run: npm run build
